# Generated by Django 4.2 on 2023-04-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField(editable=False)),
                ('x_rapport', models.JSONField(default={'test': ''})),
                ('prn', models.JSONField(default=['197504049292'])),
            ],
        ),
    ]
