# Generated by Django 4.2.8 on 2023-12-19 12:31

import KasaRegister.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PersonalNumber', '0004_alter_mobile_user_personal_number'),
        ('Revisorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('the_file', models.FileField(upload_to=KasaRegister.models.get_id_path)),
            ],
        ),
        migrations.CreateModel(
            name='KasaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('adress', models.TextField(default='{"adress":"", "postnummer":""}', max_length=200)),
                ('fcm_token', models.TextField()),
                ('notifications', models.TextField()),
                ('org_num', models.TextField()),
                ('company_name', models.TextField()),
                ('backup', models.FileField(blank=True, null=True, upload_to=KasaRegister.models.get_file_path)),
                ('backup2', models.FileField(blank=True, null=True, upload_to=KasaRegister.models.get_file_path)),
                ('backup3', models.FileField(blank=True, null=True, upload_to=KasaRegister.models.get_file_path)),
                ('xRapport', models.JSONField(default={'test': ''})),
                ('z_rapport', models.JSONField(blank=True, default={'test': ''}, null=True)),
                ('all_products', models.JSONField(default=[])),
                ('kassa_list', models.JSONField(default={'LäggTillArtikel': [], 'LäggTillHuvudgrupp': [], 'UppdateraArtikel': [], 'UppdateraHuvudgrupp': []})),
                ('huvudgrupper', models.JSONField(default=[])),
                ('bokforing', models.JSONField(default={'test': ''})),
                ('prn', models.ManyToManyField(to='PersonalNumber.mobile_user')),
                ('revisorer', models.ManyToManyField(to='Revisorer.revisor')),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(auto_created=True, max_length=12)),
                ('valid_until', models.DateField(auto_now=True)),
                ('kasa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KasaRegister.kasauser')),
            ],
        ),
    ]
