# Generated by Django 4.2.8 on 2023-12-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revisorer', '0003_revisor_file'),
        ('KasaRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasauser',
            name='revisorer',
            field=models.ManyToManyField(related_name='kasa_system', to='Revisorer.revisor'),
        ),
    ]
