# Generated by Django 4.2 on 2023-05-15 11:41

import KasaRegister.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KasaRegister', '0002_delete_prn'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('the_file', models.FileField(upload_to=KasaRegister.models.get_id_path)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('prn', models.TextField(blank=True, null=True)),
                ('adress', models.TextField(default='{"adress":"", "postnummer":""}', max_length=200)),
                ('fcm_token', models.TextField()),
                ('notifications', models.TextField()),
                ('org_num', models.TextField()),
                ('company_name', models.TextField()),
                ('backup', models.FileField(blank=True, null=True, upload_to=KasaRegister.models.get_file_path)),
                ('backup2', models.FileField(blank=True, null=True, upload_to=KasaRegister.models.get_file_path)),
                ('backup3', models.FileField(blank=True, null=True, upload_to=KasaRegister.models.get_file_path)),
                ('xRapport', models.JSONField(default={'test': ''})),
                ('z_rapport', models.JSONField(blank=True, default={'test': ''}, null=True)),
                ('all_products', models.JSONField(default=[])),
                ('kassa_list', models.JSONField(default={'LäggTillArtikel': [], 'LäggTillHuvudgrupp': [], 'UppdateraArtikel': [], 'UppdateraHuvudgrupp': []})),
                ('huvudgrupper', models.JSONField(default=[])),
            ],
        ),
    ]
