# Generated by Django 4.2.8 on 2024-01-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasaRegister', '0003_kasauser_download_alter_kasauser_kassa_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kasauser',
            name='download',
        ),
        migrations.AddField(
            model_name='kasauser',
            name='kassa_rapport',
            field=models.JSONField(default={}),
        ),
    ]
