# Generated by Django 4.2 on 2023-05-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KasaRegister', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='KasaUser',
        ),
    ]
