# Generated by Django 5.0 on 2023-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasaRegister', '0005_licence'),
        ('PersonalNumber', '0002_delete_pc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasauser',
            name='prs',
            field=models.ManyToManyField(to='PersonalNumber.mobile_user'),
        ),
    ]
