# Generated by Django 5.0 on 2023-12-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KasaRegister', '0006_kasauser_prs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kasauser',
            name='prn',
        ),
        migrations.RemoveField(
            model_name='kasauser',
            name='prs',
        ),
    ]
