# Generated by Django 5.0 on 2023-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasaRegister', '0007_remove_kasauser_prn_remove_kasauser_prs'),
        ('PersonalNumber', '0002_delete_pc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasauser',
            name='prn',
            field=models.ManyToManyField(to='PersonalNumber.mobile_user'),
        ),
    ]
