# Generated by Django 4.2 on 2023-05-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalNumber', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pc_user',
        ),
    ]
