# Generated by Django 5.0 on 2023-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalNumber', '0002_delete_pc_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile_user',
            name='password',
        ),
        migrations.AddField(
            model_name='mobile_user',
            name='certification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mobile_user',
            name='personal_number',
            field=models.CharField(max_length=12),
        ),
    ]
