# Generated by Django 5.0 on 2023-12-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalNumber', '0003_remove_mobile_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_user',
            name='personal_number',
            field=models.CharField(max_length=265, unique=True),
        ),
    ]
