# Generated by Django 4.2.8 on 2023-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revisorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisor',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
